[workspace]
members = [
    "rust_book/chapters/*", "rust_book/defining_enum",
    "rust_book/projects/*",
    "rust_by_example/*"
]

# Expliciilty pinning to use the new 2024 resolver
resolver = "2"
