[workspace]
members = [ "ownership_4",
    "rust_book/chapters/*", "rust_book/ownership_3",
    "rust_book/projects/*",
    "rust_by_example/*"
]

# Expliciilty pinning to use the new 2024 resolver
resolver = "2"
